//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeshawarDHASW.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER;Initial Catalog=DvDHAPeshawarDB;Integrated Security=True")]
        public string DvDHAPeshawarDBConnectionString {
            get {
                return ((string)(this["DvDHAPeshawarDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DHA-SERVER\\MISDEVELOPER;Initial Catalog=DvDHAPeshawarDB;User ID=sa;Pa" +
            "ssword=!#bU+Ue9")]
        public string DvDHAPeshawarDBConnectionString1 {
            get {
                return ((string)(this["DvDHAPeshawarDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DHA-SERVER;Initial Catalog=DHAPeshawarDB;Persist Security Info=True;U" +
            "ser ID=sa;Password=!#bU+Ue9")]
        public string DHAPeshawarDBConnectionString {
            get {
                return ((string)(this["DHAPeshawarDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DHA-SERVER\\MISDEVELOPER;Initial Catalog=DHAPeshawarDB;User ID=sa;Pass" +
            "word=!#bU+Ue9")]
        public string DHAPeshawarDBConnectionString1 {
            get {
                return ((string)(this["DHAPeshawarDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.0.6;Initial Catalog=DHAPeshawarDB;User ID=sa;Password=abcd@123" +
            "4")]
        public string DHAPeshawarDBConnectionString2 {
            get {
                return ((string)(this["DHAPeshawarDBConnectionString2"]));
            }
        }
    }
}
